version: '3.7'

networks:
  database_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.15.0/27
    name: database_net

volumes:
  pgadmin_data:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    networks:
      database_net:
        ipv4_address: 192.168.15.5
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strapi
      PGDATA: /data/postgres

  strapi:
    image: naskio/strapi:latest
    container_name: strapi
    hostname: strapi
    restart: unless-stopped
    networks:
      database_net:
        ipv4_address: 192.168.15.15
    ports:
      - 1337:1337
    volumes:
      - ./strapi_data:/srv/app
    depends_on:
      - postgres
    command: /bin/bash -c "npm install && strapi start"
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_HOST: '192.168.15.5'
      DATABASE_PORT: '5432'
      DATABASE_NAME: strapi
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_SSL: 'false'
      APP_KEYS: jP8pb1lYsAhnmURarewxhA==,34xnLMYHY5jiU7ONTstTqQ==
      HOST: 0.0.0.0
      PORT: 1337
      PUBLIC_URL: 'http://daemon.extinctcoder.live:1337'
      ADMIN_PUBLIC_URL: 'http://daemon.extinctcoder.live:1337/admin/abc'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    hostname: pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      database_net:
        ipv4_address: 192.168.15.4
    ports:
      - 8081:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
